import { PERMISSION_CODE } from '@neorvion/shared';
import type { AppRoute } from './types';

/**
 * ERP 业务路由与菜单的唯一配置来源。
 * 主应用只挂载 /erp，不维护这些路径。
 *
 * 未声明 permission / permissions 的路由：对当前有效成员开放。
 * 仅工作台使用该默认规则。业务页必须显式声明 read 权限。
 * showInMenu:false 仍参与页面守卫，不因隐藏菜单而放行。
 */
export const routes: AppRoute[] = [
  {
    path: '/dashboard',
    name: 'Dashboard',
    title: '工作台',
    description: 'ERP 子应用已接入。商品、仓库、库存、采购与销售订单已上线。',
    icon: 'DashboardOutlined',
    showInMenu: true,
    sort: 10,
    component: 'Dashboard',
  },
  {
    path: '/products',
    name: 'Products',
    title: '商品管理',
    icon: 'AppstoreOutlined',
    showInMenu: true,
    sort: 20,
    redirect: '/products/list',
    permission: PERMISSION_CODE.productRead,
    children: [
      {
        path: '/products/list',
        name: 'ProductList',
        title: '商品列表',
        description: '按名称、编码、SKU、类目、品牌和状态筛选本企业商品。',
        showInMenu: true,
        sort: 10,
        permission: PERMISSION_CODE.productRead,
        component: 'ProductList',
      },
      {
        path: '/product-categories',
        name: 'ProductCategories',
        title: '类目管理',
        description: '最多三级类目。删除前由服务端检查子节点和商品引用。',
        showInMenu: true,
        sort: 20,
        permission: PERMISSION_CODE.productRead,
        component: 'ProductCategories',
      },
      {
        path: '/brands',
        name: 'Brands',
        title: '品牌管理',
        description: '每个企业维护自己的品牌，编码在租户内唯一。',
        showInMenu: true,
        sort: 30,
        permission: PERMISSION_CODE.productRead,
        component: 'Brands',
      },
      {
        path: '/products/create',
        name: 'ProductCreate',
        title: '新增商品',
        description: '同一事务创建 SPU 和全部 SKU。',
        showInMenu: false,
        activeMenu: '/products/list',
        permission: PERMISSION_CODE.productCreate,
        component: 'ProductForm',
      },
      {
        path: '/products/:id/edit',
        name: 'ProductEdit',
        title: '编辑商品',
        description: '编辑 SPU 与 SKU。访问时菜单保持商品列表选中。',
        showInMenu: false,
        activeMenu: '/products/list',
        permission: PERMISSION_CODE.productUpdate,
        component: 'ProductForm',
      },
      {
        path: '/products/:id',
        name: 'ProductDetail',
        title: '商品详情',
        description: '查看 SPU 与 SKU。访问时菜单保持商品列表选中。',
        showInMenu: false,
        activeMenu: '/products/list',
        permission: PERMISSION_CODE.productRead,
        component: 'ProductDetail',
      },
    ],
  },
  {
    path: '/inventory',
    name: 'Inventory',
    title: '库存管理',
    icon: 'DatabaseOutlined',
    showInMenu: true,
    sort: 30,
    redirect: '/inventory/list',
    permission: PERMISSION_CODE.inventoryRead,
    children: [
      {
        path: '/inventory/list',
        name: 'InventoryList',
        title: '库存列表',
        description: '按仓库 + SKU 查看实际库存、预占库存与可用库存。',
        showInMenu: true,
        sort: 10,
        permission: PERMISSION_CODE.inventoryRead,
        component: 'InventoryList',
      },
      {
        path: '/inventory/transactions',
        name: 'InventoryTransactions',
        title: '库存流水',
        description: '查看库存变化历史。流水只追加，纠错请做新的调整。',
        showInMenu: true,
        sort: 20,
        permission: PERMISSION_CODE.inventoryTransactionRead,
        component: 'InventoryTransactions',
      },
      {
        path: '/outbound-orders',
        name: 'OutboundList',
        title: '销售出库',
        description: '拣货不扣库存。确认出库后实际库存和预占同时减少。',
        showInMenu: true,
        sort: 30,
        permission: PERMISSION_CODE.outboundRead,
        component: 'OutboundList',
      },
      {
        path: '/outbound-orders/:id',
        name: 'OutboundDetail',
        title: '出库单详情',
        description: '填写拣货数量并确认出库。',
        showInMenu: false,
        activeMenu: '/outbound-orders',
        permission: PERMISSION_CODE.outboundRead,
        component: 'OutboundDetail',
      },
      {
        path: '/inventory/:id',
        name: 'InventoryDetail',
        title: '库存详情',
        description: '查看仓库 + SKU 的当前账面与最近流水。',
        showInMenu: false,
        activeMenu: '/inventory/list',
        permission: PERMISSION_CODE.inventoryRead,
        component: 'InventoryDetail',
      },
    ],
  },
  {
    path: '/warehouses',
    name: 'Warehouses',
    title: '仓库管理',
    description: '维护本企业仓库档案，设置默认仓库。后续库存按仓库 + SKU 记账。',
    icon: 'ShopOutlined',
    showInMenu: true,
    sort: 40,
    permission: PERMISSION_CODE.warehouseRead,
    component: 'Warehouses',
  },
  {
    path: '/purchases',
    name: 'Purchases',
    title: '采购管理',
    icon: 'AccountBookOutlined',
    showInMenu: true,
    sort: 45,
    redirect: '/purchases/list',
    permission: PERMISSION_CODE.purchaseRead,
    children: [
      {
        path: '/purchases/list',
        name: 'PurchaseList',
        title: '采购单',
        description: '创建草稿、提交审核；确认收货后才增加库存。',
        showInMenu: true,
        sort: 10,
        permission: PERMISSION_CODE.purchaseRead,
        component: 'PurchaseList',
      },
      {
        path: '/suppliers',
        name: 'Suppliers',
        title: '供应商管理',
        description: '维护供应商档案。停用后不能新建采购单，历史单据保留。',
        showInMenu: true,
        sort: 20,
        permission: PERMISSION_CODE.supplierRead,
        component: 'Suppliers',
      },
      {
        path: '/purchase-receipts',
        name: 'PurchaseReceiptList',
        title: '采购收货',
        description: '草稿不入库。确认收货后增加实际库存，预占不变。',
        showInMenu: true,
        sort: 15,
        permission: PERMISSION_CODE.purchaseReceiptRead,
        component: 'PurchaseReceiptList',
      },
      {
        path: '/purchase-receipts/create',
        name: 'PurchaseReceiptCreate',
        title: '新建收货单',
        description: '从待收货或部分收货的采购单创建草稿。',
        showInMenu: false,
        activeMenu: '/purchase-receipts',
        permission: PERMISSION_CODE.purchaseReceiptCreate,
        component: 'PurchaseReceiptForm',
      },
      {
        path: '/purchase-receipts/:id',
        name: 'PurchaseReceiptDetail',
        title: '收货单详情',
        description: '确认后正式入库。',
        showInMenu: false,
        activeMenu: '/purchase-receipts',
        permission: PERMISSION_CODE.purchaseReceiptRead,
        component: 'PurchaseReceiptDetail',
      },
      {
        path: '/purchases/create',
        name: 'PurchaseCreate',
        title: '新建采购单',
        description: '选择供应商、仓库并添加多个 SKU。',
        showInMenu: false,
        activeMenu: '/purchases/list',
        permission: PERMISSION_CODE.purchaseCreate,
        component: 'PurchaseForm',
      },
      {
        path: '/purchases/:id/edit',
        name: 'PurchaseEdit',
        title: '编辑采购单',
        description: '仅草稿或已驳回可编辑核心字段。',
        showInMenu: false,
        activeMenu: '/purchases/list',
        permission: PERMISSION_CODE.purchaseUpdate,
        component: 'PurchaseForm',
      },
      {
        path: '/purchases/:id',
        name: 'PurchaseDetail',
        title: '采购单详情',
        description: '查看状态机、明细与审核信息。',
        showInMenu: false,
        activeMenu: '/purchases/list',
        permission: PERMISSION_CODE.purchaseRead,
        component: 'PurchaseDetail',
      },
    ],
  },
  {
    path: '/orders',
    name: 'Orders',
    title: '订单管理',
    icon: 'ShoppingCartOutlined',
    showInMenu: true,
    sort: 50,
    redirect: '/orders/list',
    permission: PERMISSION_CODE.orderRead,
    children: [
      {
        path: '/orders/list',
        name: 'SalesOrderList',
        title: '销售订单',
        description: '创建草稿、提交并确认。确认后预占库存，取消待出库订单会释放预占。',
        showInMenu: true,
        sort: 10,
        permission: PERMISSION_CODE.orderRead,
        component: 'SalesOrderList',
      },
      {
        path: '/customers',
        name: 'Customers',
        title: '客户管理',
        description: '维护客户档案。停用后不能新建订单，历史订单保留当时的收货地址。',
        showInMenu: true,
        sort: 20,
        permission: PERMISSION_CODE.customerRead,
        component: 'Customers',
      },
      {
        path: '/orders/create',
        name: 'SalesOrderCreate',
        title: '新建销售订单',
        description: '选择客户、履约仓库并添加多个 SKU。保存草稿不预占库存。',
        showInMenu: false,
        activeMenu: '/orders/list',
        permission: PERMISSION_CODE.orderCreate,
        component: 'SalesOrderForm',
      },
      {
        path: '/orders/:id/edit',
        name: 'SalesOrderEdit',
        title: '编辑销售订单',
        description: '仅草稿可修改客户、仓库、收货信息和明细。',
        showInMenu: false,
        activeMenu: '/orders/list',
        permission: PERMISSION_CODE.orderUpdate,
        component: 'SalesOrderForm',
      },
      {
        path: '/orders/:id',
        name: 'SalesOrderDetail',
        title: '销售订单详情',
        description: '查看状态、收货快照和库存预占。',
        showInMenu: false,
        activeMenu: '/orders/list',
        permission: PERMISSION_CODE.orderRead,
        component: 'SalesOrderDetail',
      },
    ],
  },
  {
    path: '/system',
    name: 'System',
    title: '系统管理',
    icon: 'SettingOutlined',
    showInMenu: true,
    sort: 60,
    redirect: '/system/members',
    children: [
      {
        path: '/system/members',
        name: 'Members',
        title: '成员管理',
        description: '添加已有账号或创建新账号，分配角色并启停、移除成员。',
        showInMenu: true,
        sort: 10,
        permission: PERMISSION_CODE.tenantMemberRead,
        component: 'Members',
      },
      {
        path: '/system/members/:memberId',
        name: 'MemberDetail',
        title: '成员详情',
        showInMenu: false,
        activeMenu: '/system/members',
        permission: PERMISSION_CODE.tenantMemberRead,
        component: 'Members',
      },
      {
        path: '/system/roles',
        name: 'Roles',
        title: '角色管理',
        description: '查看系统角色，维护自定义角色与权限。',
        showInMenu: true,
        sort: 20,
        permission: PERMISSION_CODE.tenantRoleRead,
        component: 'Roles',
      },
      {
        path: '/system/permissions',
        name: 'Permissions',
        title: '权限目录',
        description: '只读查看系统当前支持的权限编码，不能由企业自行增删。',
        showInMenu: true,
        sort: 30,
        permission: PERMISSION_CODE.tenantPermissionRead,
        component: 'Permissions',
      },
    ],
  },
];

export const DEFAULT_REDIRECT = '/dashboard';
