import { PERMISSION_CODE } from '@neorvion/shared';
import type { AppRoute } from './types';

/**
 * ERP 业务路由与菜单的唯一配置来源。
 * 主应用只挂载 /erp，不维护这些路径。
 *
 * 未声明 permission / permissions 的路由：对当前有效成员开放。
 * 仅工作台使用该默认规则。业务页必须显式声明 read 权限。
 * showInMenu:false 仍参与页面守卫，不因隐藏菜单而放行。
 */
export const routes: AppRoute[] = [
  {
    path: '/dashboard',
    name: 'Dashboard',
    title: '工作台',
    description: 'ERP 子应用已接入。商品、仓库、库存与采购管理已上线；订单等后续版本实现。',
    icon: 'DashboardOutlined',
    showInMenu: true,
    sort: 10,
    component: 'Dashboard',
  },
  {
    path: '/products',
    name: 'Products',
    title: '商品管理',
    icon: 'AppstoreOutlined',
    showInMenu: true,
    sort: 20,
    redirect: '/products/list',
    permission: PERMISSION_CODE.productRead,
    children: [
      {
        path: '/products/list',
        name: 'ProductList',
        title: '商品列表',
        description: '按名称、编码、SKU、类目、品牌和状态筛选本企业商品。',
        showInMenu: true,
        sort: 10,
        permission: PERMISSION_CODE.productRead,
        component: 'ProductList',
      },
      {
        path: '/product-categories',
        name: 'ProductCategories',
        title: '类目管理',
        description: '最多三级类目。删除前由服务端检查子节点和商品引用。',
        showInMenu: true,
        sort: 20,
        permission: PERMISSION_CODE.productRead,
        component: 'ProductCategories',
      },
      {
        path: '/brands',
        name: 'Brands',
        title: '品牌管理',
        description: '每个企业维护自己的品牌，编码在租户内唯一。',
        showInMenu: true,
        sort: 30,
        permission: PERMISSION_CODE.productRead,
        component: 'Brands',
      },
      {
        path: '/products/create',
        name: 'ProductCreate',
        title: '新增商品',
        description: '同一事务创建 SPU 和全部 SKU。',
        showInMenu: false,
        activeMenu: '/products/list',
        permission: PERMISSION_CODE.productCreate,
        component: 'ProductForm',
      },
      {
        path: '/products/:id/edit',
        name: 'ProductEdit',
        title: '编辑商品',
        description: '编辑 SPU 与 SKU。访问时菜单保持商品列表选中。',
        showInMenu: false,
        activeMenu: '/products/list',
        permission: PERMISSION_CODE.productUpdate,
        component: 'ProductForm',
      },
      {
        path: '/products/:id',
        name: 'ProductDetail',
        title: '商品详情',
        description: '查看 SPU 与 SKU。访问时菜单保持商品列表选中。',
        showInMenu: false,
        activeMenu: '/products/list',
        permission: PERMISSION_CODE.productRead,
        component: 'ProductDetail',
      },
    ],
  },
  {
    path: '/inventory',
    name: 'Inventory',
    title: '库存管理',
    icon: 'DatabaseOutlined',
    showInMenu: true,
    sort: 30,
    redirect: '/inventory/list',
    permission: PERMISSION_CODE.inventoryRead,
    children: [
      {
        path: '/inventory/list',
        name: 'InventoryList',
        title: '库存列表',
        description: '按仓库 + SKU 查看实际库存、预占库存与可用库存。',
        showInMenu: true,
        sort: 10,
        permission: PERMISSION_CODE.inventoryRead,
        component: 'InventoryList',
      },
      {
        path: '/inventory/transactions',
        name: 'InventoryTransactions',
        title: '库存流水',
        description: '查看库存变化历史。流水只追加，纠错请做新的调整。',
        showInMenu: true,
        sort: 20,
        permission: PERMISSION_CODE.inventoryTransactionRead,
        component: 'InventoryTransactions',
      },
      {
        path: '/inventory/:id',
        name: 'InventoryDetail',
        title: '库存详情',
        description: '查看仓库 + SKU 的当前账面与最近流水。',
        showInMenu: false,
        activeMenu: '/inventory/list',
        permission: PERMISSION_CODE.inventoryRead,
        component: 'InventoryDetail',
      },
    ],
  },
  {
    path: '/warehouses',
    name: 'Warehouses',
    title: '仓库管理',
    description: '维护本企业仓库档案，设置默认仓库。后续库存按仓库 + SKU 记账。',
    icon: 'ShopOutlined',
    showInMenu: true,
    sort: 40,
    permission: PERMISSION_CODE.warehouseRead,
    component: 'Warehouses',
  },
  {
    path: '/purchases',
    name: 'Purchases',
    title: '采购管理',
    icon: 'AccountBookOutlined',
    showInMenu: true,
    sort: 45,
    redirect: '/purchases/list',
    permission: PERMISSION_CODE.purchaseRead,
    children: [
      {
        path: '/purchases/list',
        name: 'PurchaseList',
        title: '采购单',
        description: '创建草稿、提交审核；审核通过后进入待收货，本版不增加库存。',
        showInMenu: true,
        sort: 10,
        permission: PERMISSION_CODE.purchaseRead,
        component: 'PurchaseList',
      },
      {
        path: '/suppliers',
        name: 'Suppliers',
        title: '供应商管理',
        description: '维护供应商档案。停用后不能新建采购单，历史单据保留。',
        showInMenu: true,
        sort: 20,
        permission: PERMISSION_CODE.supplierRead,
        component: 'Suppliers',
      },
      {
        path: '/purchases/create',
        name: 'PurchaseCreate',
        title: '新建采购单',
        description: '选择供应商、仓库并添加多个 SKU。',
        showInMenu: false,
        activeMenu: '/purchases/list',
        permission: PERMISSION_CODE.purchaseCreate,
        component: 'PurchaseForm',
      },
      {
        path: '/purchases/:id/edit',
        name: 'PurchaseEdit',
        title: '编辑采购单',
        description: '仅草稿或已驳回可编辑核心字段。',
        showInMenu: false,
        activeMenu: '/purchases/list',
        permission: PERMISSION_CODE.purchaseUpdate,
        component: 'PurchaseForm',
      },
      {
        path: '/purchases/:id',
        name: 'PurchaseDetail',
        title: '采购单详情',
        description: '查看状态机、明细与审核信息。',
        showInMenu: false,
        activeMenu: '/purchases/list',
        permission: PERMISSION_CODE.purchaseRead,
        component: 'PurchaseDetail',
      },
    ],
  },
  {
    path: '/orders',
    name: 'Orders',
    title: '订单',
    description: '后续版本实现审核、预占、出库与发货。',
    icon: 'ShoppingCartOutlined',
    showInMenu: true,
    sort: 50,
    permission: PERMISSION_CODE.orderRead,
    component: 'Placeholder',
  },
  {
    path: '/system',
    name: 'System',
    title: '系统管理',
    icon: 'SettingOutlined',
    showInMenu: true,
    sort: 60,
    redirect: '/system/members',
    children: [
      {
        path: '/system/members',
        name: 'Members',
        title: '成员管理',
        description: '添加已有账号或创建新账号，分配角色并启停、移除成员。',
        showInMenu: true,
        sort: 10,
        permission: PERMISSION_CODE.tenantMemberRead,
        component: 'Members',
      },
      {
        path: '/system/members/:memberId',
        name: 'MemberDetail',
        title: '成员详情',
        showInMenu: false,
        activeMenu: '/system/members',
        permission: PERMISSION_CODE.tenantMemberRead,
        component: 'Members',
      },
      {
        path: '/system/roles',
        name: 'Roles',
        title: '角色管理',
        description: '查看系统角色，维护自定义角色与权限。',
        showInMenu: true,
        sort: 20,
        permission: PERMISSION_CODE.tenantRoleRead,
        component: 'Roles',
      },
      {
        path: '/system/permissions',
        name: 'Permissions',
        title: '权限目录',
        description: '只读查看系统当前支持的权限编码，不能由企业自行增删。',
        showInMenu: true,
        sort: 30,
        permission: PERMISSION_CODE.tenantPermissionRead,
        component: 'Permissions',
      },
    ],
  },
];

export const DEFAULT_REDIRECT = '/dashboard';
