import { PERMISSION_CODE } from '@neorvion/shared';
import type { AppRoute } from './types';

/**
 * ERP 业务路由与菜单的唯一配置来源。
 * 主应用只挂载 /erp，不维护这些路径。
 *
 * 未声明 permission / permissions 的路由：对当前有效成员开放。
 * 仅工作台使用该默认规则。业务占位页必须显式声明 read 权限。
 * showInMenu:false 仍参与页面守卫，不因隐藏菜单而放行。
 */
export const routes: AppRoute[] = [
  {
    path: '/dashboard',
    name: 'Dashboard',
    title: '工作台',
    description: 'ERP 子应用已接入。商品、库存、订单等业务页面从后续里程碑实现。',
    icon: 'DashboardOutlined',
    showInMenu: true,
    sort: 10,
    component: 'Dashboard',
  },
  {
    path: '/products',
    name: 'Products',
    title: '商品管理',
    icon: 'AppstoreOutlined',
    showInMenu: true,
    sort: 20,
    redirect: '/products/list',
    permission: PERMISSION_CODE.productRead,
    children: [
      {
        path: '/products/archive',
        name: 'ProductArchive',
        title: '商品档案',
        showInMenu: true,
        sort: 10,
        redirect: '/products/list',
        permission: PERMISSION_CODE.productRead,
        children: [
          {
            path: '/products/list',
            name: 'ProductList',
            title: '商品列表',
            description: 'M3 将实现 SPU / SKU、编码与状态筛选。',
            showInMenu: true,
            sort: 10,
            permission: PERMISSION_CODE.productRead,
            component: 'Placeholder',
          },
        ],
      },
      {
        path: '/products/create',
        name: 'ProductCreate',
        title: '新增商品',
        description: '占位页，不在菜单中展示。',
        showInMenu: false,
        activeMenu: '/products/list',
        permission: PERMISSION_CODE.productCreate,
        component: 'Placeholder',
      },
      {
        path: '/products/:id/edit',
        name: 'ProductEdit',
        title: '编辑商品',
        description: '占位页，访问时菜单保持商品列表选中。',
        showInMenu: false,
        activeMenu: '/products/list',
        permission: PERMISSION_CODE.productUpdate,
        component: 'Placeholder',
      },
      {
        path: '/products/:id',
        name: 'ProductDetail',
        title: '商品详情',
        description: '占位页，访问时菜单保持商品列表选中。',
        showInMenu: false,
        activeMenu: '/products/list',
        permission: PERMISSION_CODE.productRead,
        component: 'Placeholder',
      },
    ],
  },
  {
    path: '/inventory',
    name: 'Inventory',
    title: '库存管理',
    icon: 'DatabaseOutlined',
    showInMenu: true,
    sort: 30,
    redirect: '/inventory/list',
    permission: PERMISSION_CODE.inventoryRead,
    children: [
      {
        path: '/inventory/list',
        name: 'InventoryList',
        title: '库存列表',
        description: 'M3 将实现实际库存、预占库存与库存流水。',
        showInMenu: true,
        sort: 10,
        permission: PERMISSION_CODE.inventoryRead,
        component: 'Placeholder',
      },
    ],
  },
  {
    path: '/warehouses',
    name: 'Warehouses',
    title: '仓库',
    description: 'M3 将实现仓库启停与库存查询。',
    icon: 'ShopOutlined',
    showInMenu: true,
    sort: 40,
    permission: PERMISSION_CODE.inventoryRead,
    component: 'Placeholder',
  },
  {
    path: '/orders',
    name: 'Orders',
    title: '订单',
    description: 'M5 将实现审核、预占、出库与发货。',
    icon: 'ShoppingCartOutlined',
    showInMenu: true,
    sort: 50,
    permission: PERMISSION_CODE.orderRead,
    component: 'Placeholder',
  },
  {
    path: '/system',
    name: 'System',
    title: '系统管理',
    icon: 'SettingOutlined',
    showInMenu: true,
    sort: 60,
    redirect: '/system/members',
    children: [
      {
        path: '/system/members',
        name: 'Members',
        title: '成员管理',
        description: '添加已有账号或创建新账号，分配角色并启停、移除成员。',
        showInMenu: true,
        sort: 10,
        permission: PERMISSION_CODE.tenantMemberRead,
        component: 'Members',
      },
      {
        path: '/system/members/:memberId',
        name: 'MemberDetail',
        title: '成员详情',
        showInMenu: false,
        activeMenu: '/system/members',
        permission: PERMISSION_CODE.tenantMemberRead,
        component: 'Members',
      },
      {
        path: '/system/roles',
        name: 'Roles',
        title: '角色管理',
        description: '查看系统角色，维护自定义角色与权限。',
        showInMenu: true,
        sort: 20,
        permission: PERMISSION_CODE.tenantRoleRead,
        component: 'Roles',
      },
      {
        path: '/system/permissions',
        name: 'Permissions',
        title: '权限目录',
        description: '只读查看系统当前支持的权限编码，不能由企业自行增删。',
        showInMenu: true,
        sort: 30,
        permission: PERMISSION_CODE.tenantRoleRead,
        component: 'Permissions',
      },
    ],
  },
];

export const DEFAULT_REDIRECT = '/dashboard';
